/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author btssio
 */
public class VueRepresentation extends javax.swing.JFrame {
    
    private DefaultTableModel modeleTableRepresentation;
    
    /**
     * Creates new form GEST_BILL
     */
    public VueRepresentation() {
        initComponents();
        modeleTableRepresentation = new  DefaultTableModel();
        jTableRepresentation.setModel(modeleTableRepresentation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRepresentation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRepresentation = new javax.swing.JTable();
        jLabelRepresentationSelectionnee = new javax.swing.JLabel();
        jLabelLaRepresentation = new javax.swing.JLabel();
        jLabelLaRepresentation2 = new javax.swing.JLabel();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonVendre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRepresentation.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabelRepresentation.setText("Représentation");

        jTableRepresentation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, ""},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "LIEU", "GROUPE", "DATE", "DEBUT", "FIN"
            }
        ));
        jScrollPane1.setViewportView(jTableRepresentation);

        jLabelRepresentationSelectionnee.setText("Representation selectionnée :");

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnnulerMouseClicked(evt);
            }
        });

        jButtonVendre.setText("Vendre");
        jButtonVendre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVendreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelLaRepresentation2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(101, 101, 101))
                    .addComponent(jLabelLaRepresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRepresentationSelectionnee)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jButtonVendre)
                .addGap(87, 87, 87)
                .addComponent(jButtonAnnuler)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRepresentation)
                .addGap(367, 367, 367))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRepresentationSelectionnee)
                .addGap(18, 18, 18)
                .addComponent(jLabelLaRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLaRepresentation2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVendre)
                    .addComponent(jButtonAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonAnnuler() {
        return jButtonAnnuler;
    }

    public void setjButtonAnnuler(JButton jButtonAnnuler) {
        this.jButtonAnnuler = jButtonAnnuler;
    }

    public JButton getjButtonVendre() {
        return jButtonVendre;
    }

    public void setjButtonVendre(JButton jButtonVendre) {
        this.jButtonVendre = jButtonVendre;
    }

    private void jButtonAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnnulerMouseClicked
      
    }//GEN-LAST:event_jButtonAnnulerMouseClicked

    private void jButtonVendreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVendreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendreMouseClicked

    public JLabel getjLabelLaRepresentation2() {
        return jLabelLaRepresentation2;
    }

    public void setjLabelLaRepresentation2(JLabel jLabelLaRepresentation2) {
        this.jLabelLaRepresentation2 = jLabelLaRepresentation2;
    }

    public JTable getjTableRepresentation() {
        return jTableRepresentation;
    }

    public void setjTableRepresentation(JTable jTableRepresentation) {
        this.jTableRepresentation = jTableRepresentation;
    }

   public DefaultTableModel getModeleTableRepresentation() {
        return modeleTableRepresentation;
    }

    public JLabel getjLabelLaRepresentation() {
        return jLabelLaRepresentation;
    }

    public void setjLabelLaRepresentation(JLabel jLabelLaRepresentation) {
        this.jLabelLaRepresentation = jLabelLaRepresentation;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonVendre;
    private javax.swing.JLabel jLabelLaRepresentation;
    private javax.swing.JLabel jLabelLaRepresentation2;
    private javax.swing.JLabel jLabelRepresentation;
    private javax.swing.JLabel jLabelRepresentationSelectionnee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRepresentation;
    // End of variables declaration//GEN-END:variables
}
